### ISSUE TITLE
Merge with latest kernel by ASUS

### ISSUE THREAD

**Issue by joaofl** [LineageOS-Zenfone3/android_device_asus_Z017#4] opened 2017-09-05 16:27 UTC
@mdigiacomi 
Just one question, that may be silly.

By merging your current kernel with the latest one provided by Asus, wouldn't solve the issues related to the fingerprint, battery and some others?

Asus released one last month, which I have compared with the branch of yours, and have showed several differences. I wonder how much this differences impact on the overall functionality.

Here is the [link](http://dlcdnet.asus.com/pub/ASUS/ZenFone/ZE520KL/ZE520KL_Kernel_14.2020.1708.56.zip?_ga=2.268365581.2064824362.1504626574-421445596.1499187333) for the kernel im refering to.

**Comment by mdigiacomi** [comment] 2017-09-05 16:35
I think it might be only an issue if the issue is the kernel and not the middleware. I was holding off on merging a new kernel until I fixed this. maybe I should just merge and see.

**Comment by joaofl** [comment] 2017-09-05 16:44
And how do you actually figure out which bug is where? I'm really curious to understand how this whole development process work, and eventually be able to help. So please let me know how.

I could at least debug new releases.

**Comment by mdigiacomi** [comment] 2017-09-05 16:49
Honestly I'm new to Android Development. I mostly do Web Development and DevOps @ work. I've spent the better part of 1.5 weeks getting familiar with the build process and android build dependencies. The biggest challenge is being able to build android fast.

**Comment by joaofl** [comment] 2017-09-05 16:54
Yes.... I get it. Same here. I'm a developer, but mostly to microcontrollers and low level firmwares. Some high level C/C++ as well, but never done anything from low linux kernel to middlewares and everything else.

I just gave a try on compiling the new kernel, but had issues really soon on the compilation. I have compiled before, but using this Linaro distributions. How have you managed to do it?

Maybe we can have a virtual machine image to compile from...

**Comment by mdigiacomi** [comment] 2017-09-05 17:04
I'm actually running a full Server to build this thing. I am using Jenkins for the build manager which transfers the compiled binary to my build directory in testing.

Server Specs - 
8 Cores(16 Threads)
128GB Ram
6??GB SSD RAID 1E (4 240GB SSD)
960GB RAID 0 (4 240GB SSD)

Jenkins Link: https://jenkins.michaeldigiacomi.com/job/Android/job/Z012%20and%20Z017%20Builds/job/LineageOS/

Build Output: 
https://builds.michaeldigiacomi.com/Testing

 I find the kernel builds best along with the other pieces in android. I'm checking in the latest version now hopefully and then I can perform another Build

**Comment by joaofl** [comment] 2017-09-05 17:13
Thats heavy metal stuff. Dont know how jenkings work, even less about the entire building process, but seems rather complicated. 

Let me know If I can help with something!

**Comment by mdigiacomi** [comment] 2017-09-08 11:41
I have merged the latest kernel code into the kernel except for the sdcard stuff as there was a lot of customization done by shakalaca and I don't want to tackle it if it works. 

https://github.com/LineageOS-Zenfone3/android_kernel_asus_ze520kl/tree/android-7.0

**Closed** 2017-09-08 18:14 UTC
Labels: enhancement
